### ISSUE TITLE
enhancement(trusty-mpm): worktree provisioning skips install/build, breaking the first gate run

### ISSUE THREAD

**Issue by bobmatnyc** [bobmatnyc/trusty-tools#7381]
Symptom: a worktree provisioned with `isolation:"worktree"` starts with no `node_modules` and no built workspace `dist`, so the first gate run fails on module resolution (`Cannot find module 'react/jsx-runtime'`, later `.../design-system/dist/index.js`).

Cause: worktree provisioning creates the git tree only; it does not run the project's package install or workspace build, and the dispatch template does not name those commands either.

Proposed change: run the project's install (and workspace build, where one is needed before the app resolves) as part of worktree provisioning, or have the dispatch template state the two commands explicitly (e.g. `pnpm install --frozen-lockfile`, `npx turbo run build --filter=<app>^...`).

Evidence: three engineers in one session each paid a separate install round trip on the same missing-module error. Origin: adaptive-crm PM session 2026-09-10, evening.

🤖🤖🤖 Generated with trusty-mpm — https://github.com/bobmatnyc/trusty-tools

**Comment by bobmatnyc** [comment]
tm issue transition: `open` → `status:in-progress`

**Comment by bobmatnyc** [comment]
Claimed by session trusty-tools-95 (tmux tm-dogfood:0:@1), 2026-09-11. prompt-engineer dispatched — one doc-only PR against crates/trusty-agents-common agent assets.

🤖🤖🤖 Generated with trusty-mpm — https://github.com/bobmatnyc/trusty-tools

**Comment by bobmatnyc** [comment]
tm issue transition: `status:in-progress` → `status:coded`

Fix on PR [#7417](https://github.com/bobmatnyc/trusty-tools/pull/7417), head ca9dbad45, auto-merge armed; doc-only change to the bundled agent instruction assets. Session trusty-tools-95, 2026-09-11.

**Comment by bobmatnyc** [comment]
tm issue transition: `status:coded` → `status:merged`

**Comment by bobmatnyc** [comment]
PR [#7417](https://github.com/bobmatnyc/trusty-tools/pull/7417) merged as [ab4ca36](https://github.com/bobmatnyc/trusty-tools/commit/ab4ca36f19dad82d6ba4cd77514290963c95d986); live verification pending. Session trusty-tools-95, 2026-09-11.

**Comment by bobmatnyc** [comment]
Additional evidence and a distinct failure mode, from #7427 PR-3 (rust-engineer, 2026-09-11), same root cause as this issue: a fresh `isolation:"worktree"` checkout carries no `node_modules`, and nothing in the dispatch brief names the install step before the UI gates (`pnpm test:unit`/`check`/`build`).

Here the failure mode was not the "Cannot find module" crash this issue already documents -- it was a silent success: the engineer ran one gate from the main checkout by mistake (read-only, no source written), which already has `node_modules` installed, so the gate passed while proving nothing about the actual change.

Since the merged fix's live verification is still pending, flagging this as a second failure shape worth covering in that verification: a UI gate dispatch brief should also state which tree to run from, not only the install command. Candidate homes for the fix, per the original proposal: BASE-AGENT/BASE-ENGINEER assets under crates/trusty-mpm/src/assets, or the tm-delegation-patterns skill.

Generated with trusty-mpm -- https://github.com/bobmatnyc/trusty-tools

**Comment by bobmatnyc** [comment]
Assets live in crates/trusty-agents-common and deploy with the trusty-agents product, not the tm claude-config agents dir; verification belongs to the tm-agents session's next tagent install.

🤖🤖🤖 Generated with trusty-mpm — https://github.com/bobmatnyc/trusty-tools

**Comment by bobmatnyc** [comment]
New instance, 2026-09-11, project adaptive-crm (pnpm/Turbo monorepo): a worktree-isolated dispatch provisioned only the checkout — every test suite failed with `ERR_MODULE_NOT_FOUND …/@adaptive-crm/app-session/dist/index.js` until the agent ran `pnpm install --frozen-lockfile` and `turbo run build --filter=<pkg>^... --force` by hand. Confirms the fix: run the project's install + dependency build at worktree provisioning, or state both commands literally in the dispatch template.

Reported from a trusty-mpm session on project adaptive-crm, 2026-09-11.

🤖🤖🤖 Generated with trusty-mpm — https://github.com/bobmatnyc/trusty-tools

**Comment by bobmatnyc** [comment]
tm issue transition: `status:merged` → `status:tested`

**Comment by bobmatnyc** [comment]
tm issue transition: `status:tested` → `closed`

Live verification at installed tm 1.5.35 (built from e9c9306d8). BASE-ENGINEER.md:151 Dependency Verification / :165 Cannot find module install-before-gates guidance shipped and dispatched live in this session.
