### ISSUE TITLE
trusty-memory: slim build (default-features=false) fails — dream_ops uses feature-gated crate::web

### ISSUE THREAD

**Issue by bobmatnyc** [bobmatnyc/trusty-tools#2049]
## Summary

`trusty-memory` fails to compile with `--no-default-features` (the slim library surface introduced in #226), breaking any dependent that opts out of `axum-server` — notably `trusty-agents`, which declares `trusty-memory = { ..., default-features = false }`.

```
error[E0433]: cannot find `web` in `crate`
  --> crates/trusty-memory/src/tools/dream_ops.rs:56
   |
56 |     let cfg = crate::web::load_user_config().unwrap_or_default();
   |                      ^^^ could not find `web` in the crate root
```

## Root cause

`pub mod web` is `#[cfg(feature = "axum-server")]`-gated (`lib.rs:149`), but `tools` (and `tools::dream_ops`) is compiled unconditionally. `dream_ops.rs:56` reaches the user-config loader through the `crate::web::load_user_config` re-export, which only exists when `axum-server` is on. The `chat` callers of the same re-export are fine because `mod chat` is itself `axum-server`-gated.

This is exactly the case #226 anticipated: `service::load_user_config` is "the axum-free home of the loader; the `web::` re-export only exists for the HTTP handlers" (see the comment on `chat_provider()` at `lib.rs:1244`, which already routes around it). `dream_ops` was simply missed.

## Fix

Point `dream_ops.rs` at `crate::service::load_user_config()` (the axum-free re-export, `service/mod.rs:28`) instead of `crate::web::load_user_config()`. One line; both feature combinations then build.

## Repro

```
cargo check -p trusty-memory --no-default-features   # fails on main
cargo check -p trusty-agents                          # fails on main (transitively)
```
